# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/vicen/OneDrive/Escritorio/Septimo Semestre/SEP/Ayudantias/Ayudantia 1/Zybo-Z7-Master.xdc

# Block Designs: bd/Proyecto_1_sep/Proyecto_1_sep.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Proyecto_1_sep || ORIG_REF_NAME==Proyecto_1_sep} -quiet] -quiet

# IP: bd/Proyecto_1_sep/ip/Proyecto_1_sep_RAM_test_0_0/Proyecto_1_sep_RAM_test_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Proyecto_1_sep_RAM_test_0_0 || ORIG_REF_NAME==Proyecto_1_sep_RAM_test_0_0} -quiet] -quiet

# IP: bd/Proyecto_1_sep/ip/Proyecto_1_sep_ila_0_0/Proyecto_1_sep_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Proyecto_1_sep_ila_0_0 || ORIG_REF_NAME==Proyecto_1_sep_ila_0_0} -quiet] -quiet

# IP: bd/Proyecto_1_sep/ip/Proyecto_1_sep_Dientes_de_sierra_0_0/Proyecto_1_sep_Dientes_de_sierra_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Proyecto_1_sep_Dientes_de_sierra_0_0 || ORIG_REF_NAME==Proyecto_1_sep_Dientes_de_sierra_0_0} -quiet] -quiet

# IP: bd/Proyecto_1_sep/ip/Proyecto_1_sep_Sel_frec_0_0/Proyecto_1_sep_Sel_frec_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Proyecto_1_sep_Sel_frec_0_0 || ORIG_REF_NAME==Proyecto_1_sep_Sel_frec_0_0} -quiet] -quiet

# XDC: bd/Proyecto_1_sep/Proyecto_1_sep_ooc.xdc
