# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/Pato/Desktop/Universida/2024-1/SEP/IEE2463_P1/Zybo-Z7-Master.xdc

# Block Designs: bd/Proyecto_1_sep/Proyecto_1_sep.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Proyecto_1_sep || ORIG_REF_NAME==Proyecto_1_sep} -quiet] -quiet

# IP: bd/Proyecto_1_sep/ip/Proyecto_1_sep_vio_0_0/Proyecto_1_sep_vio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Proyecto_1_sep_vio_0_0 || ORIG_REF_NAME==Proyecto_1_sep_vio_0_0} -quiet] -quiet

# IP: bd/Proyecto_1_sep/ip/Proyecto_1_sep_Sel_frec_0_0/Proyecto_1_sep_Sel_frec_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Proyecto_1_sep_Sel_frec_0_0 || ORIG_REF_NAME==Proyecto_1_sep_Sel_frec_0_0} -quiet] -quiet

# IP: bd/Proyecto_1_sep/ip/Proyecto_1_sep_Sel_funcion_0_0/Proyecto_1_sep_Sel_funcion_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Proyecto_1_sep_Sel_funcion_0_0 || ORIG_REF_NAME==Proyecto_1_sep_Sel_funcion_0_0} -quiet] -quiet

# IP: bd/Proyecto_1_sep/ip/Proyecto_1_sep_Math_0_0/Proyecto_1_sep_Math_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Proyecto_1_sep_Math_0_0 || ORIG_REF_NAME==Proyecto_1_sep_Math_0_0} -quiet] -quiet

# IP: bd/Proyecto_1_sep/ip/Proyecto_1_sep_ila_0_0/Proyecto_1_sep_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Proyecto_1_sep_ila_0_0 || ORIG_REF_NAME==Proyecto_1_sep_ila_0_0} -quiet] -quiet

# IP: bd/Proyecto_1_sep/ip/Proyecto_1_sep_generador_f_0_0/Proyecto_1_sep_generador_f_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Proyecto_1_sep_generador_f_0_0 || ORIG_REF_NAME==Proyecto_1_sep_generador_f_0_0} -quiet] -quiet

# IP: bd/Proyecto_1_sep/ip/Proyecto_1_sep_SINE_RAM_0_0/Proyecto_1_sep_SINE_RAM_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Proyecto_1_sep_SINE_RAM_0_0 || ORIG_REF_NAME==Proyecto_1_sep_SINE_RAM_0_0} -quiet] -quiet

# IP: bd/Proyecto_1_sep/ip/Proyecto_1_sep_RAM_FREC_0_0/Proyecto_1_sep_RAM_FREC_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Proyecto_1_sep_RAM_FREC_0_0 || ORIG_REF_NAME==Proyecto_1_sep_RAM_FREC_0_0} -quiet] -quiet

# IP: bd/Proyecto_1_sep/ip/Proyecto_1_sep_axi_traffic_gen_0_0/Proyecto_1_sep_axi_traffic_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Proyecto_1_sep_axi_traffic_gen_0_0 || ORIG_REF_NAME==Proyecto_1_sep_axi_traffic_gen_0_0} -quiet] -quiet

# IP: bd/Proyecto_1_sep/ip/Proyecto_1_sep_axi_traffic_gen_1_0/Proyecto_1_sep_axi_traffic_gen_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Proyecto_1_sep_axi_traffic_gen_1_0 || ORIG_REF_NAME==Proyecto_1_sep_axi_traffic_gen_1_0} -quiet] -quiet

# IP: bd/Proyecto_1_sep/ip/Proyecto_1_sep_axi_traffic_gen_2_0/Proyecto_1_sep_axi_traffic_gen_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Proyecto_1_sep_axi_traffic_gen_2_0 || ORIG_REF_NAME==Proyecto_1_sep_axi_traffic_gen_2_0} -quiet] -quiet

# IP: bd/Proyecto_1_sep/ip/Proyecto_1_sep_rst_clk_100M_0/Proyecto_1_sep_rst_clk_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Proyecto_1_sep_rst_clk_100M_0 || ORIG_REF_NAME==Proyecto_1_sep_rst_clk_100M_0} -quiet] -quiet

# IP: bd/Proyecto_1_sep/ip/Proyecto_1_sep_clk_wiz_0/Proyecto_1_sep_clk_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Proyecto_1_sep_clk_wiz_0 || ORIG_REF_NAME==Proyecto_1_sep_clk_wiz_0} -quiet] -quiet

# IP: bd/Proyecto_1_sep/ip/Proyecto_1_sep_axi_smc_1_3/Proyecto_1_sep_axi_smc_1_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Proyecto_1_sep_axi_smc_1_3 || ORIG_REF_NAME==Proyecto_1_sep_axi_smc_1_3} -quiet] -quiet

# IP: bd/Proyecto_1_sep/ip/Proyecto_1_sep_axi_traffic_gen_2_axi_periph_1/Proyecto_1_sep_axi_traffic_gen_2_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Proyecto_1_sep_axi_traffic_gen_2_axi_periph_1 || ORIG_REF_NAME==Proyecto_1_sep_axi_traffic_gen_2_axi_periph_1} -quiet] -quiet

# IP: bd/Proyecto_1_sep/ip/Proyecto_1_sep_axi_smc_5/Proyecto_1_sep_axi_smc_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Proyecto_1_sep_axi_smc_5 || ORIG_REF_NAME==Proyecto_1_sep_axi_smc_5} -quiet] -quiet

# IP: bd/Proyecto_1_sep/ip/Proyecto_1_sep_ila_1_0/Proyecto_1_sep_ila_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Proyecto_1_sep_ila_1_0 || ORIG_REF_NAME==Proyecto_1_sep_ila_1_0} -quiet] -quiet

# IP: bd/Proyecto_1_sep/ip/Proyecto_1_sep_ila_1_1/Proyecto_1_sep_ila_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Proyecto_1_sep_ila_1_1 || ORIG_REF_NAME==Proyecto_1_sep_ila_1_1} -quiet] -quiet

# XDC: bd/Proyecto_1_sep/Proyecto_1_sep_ooc.xdc
