webtalk_init -webtalk_dir C:/Users/vicen/OneDrive/Escritorio/Septimo Semestre/SEP/Proyecto1/IP_Cores/generador_f/generador_f.sim/sim_1/behav/xsim/xsim.dir/generador_f_TB_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat May 11 21:48:48 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "f9583e3d-1879-4da9-8d92-a11706a4a6ef" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "682664cdf9bc42e19d2c0d7ee8f57db7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "5" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 5700U with Radeon Graphics         " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1797 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "20 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "5" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7824_KB" -context "xsim\\usage"
webtalk_transmit -clientid 227188474 -regid "" -xml C:/Users/vicen/OneDrive/Escritorio/Septimo Semestre/SEP/Proyecto1/IP_Cores/generador_f/generador_f.sim/sim_1/behav/xsim/xsim.dir/generador_f_TB_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/vicen/OneDrive/Escritorio/Septimo Semestre/SEP/Proyecto1/IP_Cores/generador_f/generador_f.sim/sim_1/behav/xsim/xsim.dir/generador_f_TB_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/vicen/OneDrive/Escritorio/Septimo Semestre/SEP/Proyecto1/IP_Cores/generador_f/generador_f.sim/sim_1/behav/xsim/xsim.dir/generador_f_TB_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
