# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Pato/Desktop/Universida/2024-1/SEP/IEE2463_P1/Proyecto_1/proyecto_1.srcs/sources_1/bd/Proyecto_1_sep/ip/Proyecto_1_sep_axi_traffic_gen_2_0/Proyecto_1_sep_axi_traffic_gen_2_0.xci
# IP: The module: 'Proyecto_1_sep_axi_traffic_gen_2_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Pato/Desktop/Universida/2024-1/SEP/IEE2463_P1/Proyecto_1/proyecto_1.srcs/sources_1/bd/Proyecto_1_sep/ip/Proyecto_1_sep_axi_traffic_gen_2_0/Proyecto_1_sep_axi_traffic_gen_2_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Proyecto_1_sep_axi_traffic_gen_2_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/Pato/Desktop/Universida/2024-1/SEP/IEE2463_P1/Proyecto_1/proyecto_1.srcs/sources_1/bd/Proyecto_1_sep/ip/Proyecto_1_sep_axi_traffic_gen_2_0/Proyecto_1_sep_axi_traffic_gen_2_0.xci
# IP: The module: 'Proyecto_1_sep_axi_traffic_gen_2_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Pato/Desktop/Universida/2024-1/SEP/IEE2463_P1/Proyecto_1/proyecto_1.srcs/sources_1/bd/Proyecto_1_sep/ip/Proyecto_1_sep_axi_traffic_gen_2_0/Proyecto_1_sep_axi_traffic_gen_2_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Proyecto_1_sep_axi_traffic_gen_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
